
/*
	Copyright 2023 Efabless Corp.

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py on 2023-10-06

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#ifndef IO_TYPES
#define IO_TYPES
#define   __R     volatile const unsigned int
#define   __W     volatile       unsigned int
#define   __RW    volatile       unsigned int
#endif

#define UART_TXDATA_REG_WDATA		0
#define UART_TXDATA_REG_WDATA_LEN	8
#define UART_RXDATA_REG_RDATA		0
#define UART_RXDATA_REG_RDATA_LEN	8
#define UART_PRESCALE_REG_PRESCALE		0
#define UART_PRESCALE_REG_PRESCALE_LEN	16
#define UART_TXFIFOLEVEL_REG_LEVEL		0
#define UART_TXFIFOLEVEL_REG_LEVEL_LEN	4
#define UART_RXFIFOLEVEL_REG_LEVEL		0
#define UART_RXFIFOLEVEL_REG_LEVEL_LEN	4
#define UART_TXFIFOT_REG_VALUE		0
#define UART_TXFIFOT_REG_VALUE_LEN	4
#define UART_RXFIFOT_REG_VALUE		0
#define UART_RXFIFOT_REG_VALUE_LEN	4
#define UART_CONTROL_REG_EN		0
#define UART_CONTROL_REG_EN_LEN	1
#define UART_CONTROL_REG_TXEN		1
#define UART_CONTROL_REG_TXEN_LEN	1
#define UART_CONTROL_REG_RXEN		2
#define UART_CONTROL_REG_RXEN_LEN	1
#define UART_TX_EMPTY_FLAG_FLAG	0x1
#define UART_TX_BELOW_FLAG_FLAG	0x2
#define UART_RX_FULL_FLAG_FLAG	0x4
#define UART_RX_ABOVE_FLAG_FLAG	0x8

typedef struct {
	__RW	txdata;
	__RW	rxdata;
	__RW	prescale;
	__R 	TXFIFOLEVEL;
	__R 	RXFIFOLEVEL;
	__RW	TXFIFOT;
	__RW	RXFIFOT;
	__RW	control;
	__R 	reserved[952];
	__W 	icr;
	__R 	ris;
	__RW	im;
	__R 	mis;
} UART_TYPE;
