
/*
	Copyright 2023 efabless

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define EF_UART_BASE				0x00000000

#define	EF_UART_DATA_REG_ADDR		(EF_UART_BASE+0x0)
#define	EF_UART_PRESCALE_REG_ADDR		(EF_UART_BASE+0x4)
#define	EF_UART_TXFIFOTR_REG_ADDR		(EF_UART_BASE+0x8)
#define	EF_UART_RXFIFOTR_REG_ADDR		(EF_UART_BASE+0xc)
#define	EF_UART_CONTROL_REG_ADDR		(EF_UART_BASE+0x10)

#define EF_UART_DATA_REG_DATA		0
#define EF_UART_DATA_REG_DATA_LEN	7
#define EF_UART_PRESCALE_REG_PRESCALE		0
#define EF_UART_PRESCALE_REG_PRESCALE_LEN	15
#define EF_UART_TXFIFOTR_REG_TXFIFOTR		0
#define EF_UART_TXFIFOTR_REG_TXFIFOTR_LEN	4
#define EF_UART_RXFIFOTR_REG_RXFIFOTR		0
#define EF_UART_RXFIFOTR_REG_RXFIFOTR_LEN	4
#define EF_UART_CONTROL_REG_EN		0
#define EF_UART_CONTROL_REG_EN_LEN	1

volatile unsigned int * ef_uart_data	= (volatile unsigned int *) EF_UART_DATA_REG_ADDR;
volatile unsigned int * ef_uart_prescale	= (volatile unsigned int *) EF_UART_PRESCALE_REG_ADDR;
volatile unsigned int * ef_uart_txfifotr	= (volatile unsigned int *) EF_UART_TXFIFOTR_REG_ADDR;
volatile unsigned int * ef_uart_rxfifotr	= (volatile unsigned int *) EF_UART_RXFIFOTR_REG_ADDR;
volatile unsigned int * ef_uart_control	= (volatile unsigned int *) EF_UART_CONTROL_REG_ADDR;
