
/*
	Copyright 2023 efabless

	Author: Mohamed Shalan (mshalan@efabless.com)

	This file is auto-generated by wrapper_gen.py

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	    http://www.apache.org/licenses/LICENSE-2.0

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.

*/


#define EF_UART_BASE				0x00000000

#define	EF_UART_TXDATA_REG_ADDR		(EF_UART_BASE+0x0)
#define	EF_UART_RXDATA_REG_ADDR		(EF_UART_BASE+0x4)
#define	EF_UART_PRESCALE_REG_ADDR		(EF_UART_BASE+0x8)
#define	EF_UART_TXFIFOLEVEL_REG_ADDR		(EF_UART_BASE+0xc)
#define	EF_UART_RXFIFOLEVEL_REG_ADDR		(EF_UART_BASE+0x10)
#define	EF_UART_TXFIFOT_REG_ADDR		(EF_UART_BASE+0x14)
#define	EF_UART_RXFIFOT_REG_ADDR		(EF_UART_BASE+0x18)
#define	EF_UART_CONTROL_REG_ADDR		(EF_UART_BASE+0x1c)
#define	EF_UART_ICR_REG_ADDR		(EF_UART_BASE+0xf00)
#define	EF_UART_RIS_REG_ADDR		(EF_UART_BASE+0xf04)
#define	EF_UART_IM_REG_ADDR		(EF_UART_BASE+0xf08)
#define	EF_UART_MIS_REG_ADDR		(EF_UART_BASE+0xf0c)

#define EF_UART_TXDATA_REG_WDATA		0
#define EF_UART_TXDATA_REG_WDATA_LEN	8
#define EF_UART_RXDATA_REG_RDATA		0
#define EF_UART_RXDATA_REG_RDATA_LEN	8
#define EF_UART_PRESCALE_REG_PRESCALE		0
#define EF_UART_PRESCALE_REG_PRESCALE_LEN	16
#define EF_UART_TXFIFOLEVEL_REG_LEVEL		0
#define EF_UART_TXFIFOLEVEL_REG_LEVEL_LEN	4
#define EF_UART_RXFIFOLEVEL_REG_LEVEL		0
#define EF_UART_RXFIFOLEVEL_REG_LEVEL_LEN	4
#define EF_UART_TXFIFOT_REG_VALUE		0
#define EF_UART_TXFIFOT_REG_VALUE_LEN	4
#define EF_UART_RXFIFOT_REG_VALUE		0
#define EF_UART_RXFIFOT_REG_VALUE_LEN	4
#define EF_UART_CONTROL_REG_EN		0
#define EF_UART_CONTROL_REG_EN_LEN	1
#define EF_UART_CONTROL_REG_TXEN		1
#define EF_UART_CONTROL_REG_TXEN_LEN	1
#define EF_UART_CONTROL_REG_RXEN		2
#define EF_UART_CONTROL_REG_RXEN_LEN	1
#define INT_TX_EMPTY_FLAG_FLAG	0x1
#define INT_TX_BELOW_FLAG_FLAG	0x2
#define INT_RX_FULL_FLAG_FLAG	0x4
#define INT_TR_ABOVE_FLAG_FLAG	0x8

volatile unsigned int * ef_uart_PRESCALE_REG	= (volatile unsigned int *) EF_UART_PRESCALE_REG_ADDR;
volatile unsigned int * ef_uart_TXFIFOT_REG	= (volatile unsigned int *) EF_UART_TXFIFOT_REG_ADDR;
volatile unsigned int * ef_uart_RXFIFOT_REG	= (volatile unsigned int *) EF_UART_RXFIFOT_REG_ADDR;
volatile unsigned int * ef_uart_CONTROL_REG	= (volatile unsigned int *) EF_UART_CONTROL_REG_ADDR;
volatile unsigned int * ef_uart_RIS_REG	= (volatile unsigned int *) EF_UART_RIS_REG_ADDR;
volatile unsigned int * ef_uart_ICR_REG	= (volatile unsigned int *) EF_UART_ICR_REG_ADDR;
volatile unsigned int * ef_uart_IM_REG	= (volatile unsigned int *) EF_UART_IM_REG_ADDR;
